gcc 1.Basic.c -o 1.Basic.o
gcc 2.Comments.c -o 2.Comments.o
gcc 3.Output.c -o 3.Output.o
gcc 4.Input.c -o 4.Input.o
gcc 5.InitialisingVariables.c -o 5.InitialisingVariables.o
gcc 6.Datatypes.c -o 6.Datatypes.o
gcc 7.EnumsAndChar.c -o 7.EnumsAndChar.o
gcc 8.FormatSpecifiers.c -o 8.FormatSpecifiers.o
gcc 9.CLIArguments.c -o 9.CLIArguments.o
gcc 10.Challenge1.c -o 10.Challenge1.o
gcc 11.Challenge2.c -o 11.Challenge2.o
gcc 12.BasicOperators.c -o 12.BasicOperators.o
gcc 13.BitwiseOperators.c -o 13.BitwiseOperators.o
