gcc 1.Basic.c -o 1.Basic.o
gcc 2.Comments.c -o 2.Comments.o
gcc 3.Output.c -o 3.Output.o
gcc 4.Input.c -o 4.Input.o
gcc 5.InitialisingVariables.c -o 5.InitialisingVariables.o
gcc 6.Datatypes.c -o 6.Datatypes.o
gcc 7.EnumsAndChar.c -o 7.EnumsAndChar.o
gcc 8.FormatSpecifiers.c -o 8.FormatSpecifiers.o
gcc 9.CLIArguments.c -o 9.CLIArguments.o
gcc 10.Challenge1.c -o 10.Challenge1.o
gcc 11.Challenge2.c -o 11.Challenge2.o
gcc 12.BasicOperators.c -o 12.BasicOperators.o
gcc 13.BitwiseOperators.c -o 13.BitwiseOperators.o
gcc 14.Cast\&Sizeof.c -o 14.Cast\&Sizeof.o
gcc 15.Challenge3.c -o 15.Challenge3.o
gcc 16.Challenge4.c -o 16.Challenge4.o
gcc 17.IfElse.c -o 17.IfElse.o
gcc 18.IfElseIf.c -o 18.IfElseIf.o
gcc 19.Switch.c -o 19.Switch.o
gcc 20.Challenge5.c -o 20.Challenge5.o
gcc 21.RightChallenge5.c -o 21.RightChallenge5.o
gcc 22.ForLoops.c -o 22.ForLoops.o
gcc 23.Challenge6.c -o 23.Challenge6.o
gcc 24.Arrays.c -o 24.Arrays.o
gcc 25.ArrayInitialisation.c -o 25.ArrayInitialisation.o
gcc 26.MultidimensionalArray.c -o 26.MultidimensionalArray.o
gcc 27.Challenge7.c -o 27.Challenge7.o
gcc 28.RightChallenge7.c -o 28.RightChallenge7.o
gcc 29.Challenge8.c -o 29.Challenge8.o
gcc 30.Functions.c -o 30.Functions.o
gcc 31.FunctionArguments.c -o 31.FunctionArguments.o
